import type { Metadata } from "next";
import { Providers } from "./Providers";
import { Sora } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";
import React from "react";
import { ToastContainer } from "react-toastify";
import LoadingOverlay from "@/components/LoadingOverlay";
// Adjust the path to your store file

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sora.variable} antialiased`}>
        <Providers>
          <Navbar />
          <LoadingOverlay />
          {children}
          <ToastContainer
            position="top-right"
            autoClose={3000}
            hideProgressBar={false}
          />
        </Providers>
      </body>
    </html>
  );
}
